# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-27 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netpro4G', '0002_auto_20190627_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ['title']},
        ),
    ]
