# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-28 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netpro4G', '0006_auto_20190628_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.AddField(
            model_name='contact',
            name='mailUs',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
