# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netpro4G', '0007_auto_20190628_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, null=True)),
                ('service', models.CharField(max_length=60, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
