# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netpro4G', '0009_auto_20190702_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, null=True)),
                ('welcome', models.TextField(null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
