# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-08 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netpro4G', '0011_remove_aboutus_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Background', models.TextField(null=True)),
            ],
        ),
    ]
