# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netpro4G', '0014_remove_service_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Security',
        ),
        migrations.RenameField(
            model_name='security',
            old_name='service',
            new_name='security',
        ),
    ]
